name: Deploy to EC2 (SSM)

on:
  push:
    tags:
      - 'prod-*'

permissions:
  id-token: write
  contents: read

jobs:
  push-to-codecommit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::113624067602:role/GitHubActions-CodeCommit-Role
          aws-region: ap-northeast-1

      - name: Push to AWS CodeCommit
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"

          git remote add codecommit https://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/deploy-test
          git push codecommit HEAD:main --force