name: Deploy to EC2 (SSM)

on:
  push:
    tags:
      - "prod-*"  # Workflow này chỉ chạy khi có tag bắt đầu với "prod-"

permissions:
  id-token: write   # Bắt buộc để login vào AWS không cần mật khẩu
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::113624067602:role/GitHub-Deploy-Role 
          aws-region: ap-northeast-1                                  

      - name: Send Deploy Command to EC2
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=i-0e804a78c5cfeffad" \
            --comment "Auto Deploy via GitHub Actions" \
            --parameters commands="['bash /var/www/deploy-test/scripts/deploy.sh']"